# Generated by Django 5.0.2 on 2024-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_category_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Shop', 'Shop'), ('Sport', 'Sport'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
