# Generated by Django 5.0.2 on 2024-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0018_alter_task_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Shop', 'Shop'), ('Sport', 'Sport'), ('Cleaning', 'Cleaning'), ('Add New', 'Add New')], max_length=20),
        ),
    ]
