# Generated by Django 5.0.2 on 2024-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0019_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Shop', 'Shop'), ('Sport', 'Sport'), ('Travel', 'Travel'), ('Cleaning', 'Cleaning'), ('Personal', 'Personal'), ('Other', 'Other')], max_length=20),
        ),
    ]
