# Generated by Django 5.0.2 on 2024-03-20 20:53

import task_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0021_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=task_app.models.get_category_choices, max_length=20),
        ),
    ]
